### PR TITLE
Feature/cakephp rules 001

### PR DESCRIPTION
**Pull request by rochamarcelo**

### CODE REVIEW

**Comment by rochamarcelo** [comment]
Covers https://github.com/CakeDC/cakephp-phpstan/issues/20 and more

**Review by steinkel — APPROVED** [review]
:clap: nice one!

**Comment by dereuromark** [comment]
Small issue I found when running it over my app

        $this->hasOne('Articleimage')
            ->setClassName('Articleimages')
            ->setFinder('firstArticleimage');
 
This triggers
```
  300    Call to App\Model\Table\ArticlesTable::hasOne could not find the class for "Articleimage"   
```

**Comment by rochamarcelo** [comment]
Release https://github.com/CakeDC/cakephp-phpstan/pull/29 fix issue with setClassName

**Pull request merged**
